### ISSUE TITLE
Thanks for using my API

### ISSUE THREAD

**Issue by LukyVj** [isururodrigo/madamnazar#1]
Hello, 

Thanks for using my API http://madam-nazar-location-api.herokuapp.com/

If you enjoy it and wants to go the extra mile & in order to support the project you can add a link to the API documentation, in your `readme.md` 😊

This API comes at a little cost, so if you really do want to support me, feel free to use my [Patreon page](https://patreon.com/lukyvj)

I do my best to keep it up and running, let me know if you have any questions!

**Comment by isururodrigo** [comment]
Thank You for your support. Really appreciate the API it was helpful for many people!
